# KDE (Wayland); Garuda Linux

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/dracula.toml"]

[window]
dimensions = { columns = 120, lines = 30}
decorations = "Full"
opacity = 0.2
blur = true
startup_mode = "Windowed"
title = "La FLDSMDFR"
dynamic_title = false
decorations_theme_variant = "Dark"


[scrolling]
history = 10000

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular"}
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold"}
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic"}
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic"}
size = 11.70
offset = {x = 1, y = 0}
builtin_box_drawing = true

[colors]
primary.foreground = "#FCF9EA"
primary.background = "#8C00FF"
cursor.cursor = "#FCF9EA"
selection = {text = "#8C00FF", background = "#FCF9EA"}

[cursor]
style.shape = "Underline"
style.blinking = "On"
blink_interval = 350
blink_timeout = 0
unfocused_hollow = false
thickness = 0.25

[mouse]
hide_when_typing = true
