"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[╭──────────────────────────────────────────────────╮](bold brilliant_green)
[│](bold brilliant_green)$username$hostname$directory$git_branch$git_status
[│](bold brilliant_green)$os $battery$memory_usage
[│](bold brilliant_green)$python
[├──────────────────────────────────────────────────╯](bold brilliant_green)
[│](bold brilliant_green)
[╰─▶ $sudo](bold brilliant_green)
"""

palette = "catppuccin_mocha"
scan_timeout = 10

# USERNAME
[username]
format = "[TitiLM10]($style)@"
show_always = true
style_user = "bold red"

# HOSTNAME
[hostname]
disabled = false
format = "[Tnoob-dev]($style) in "
ssh_only = false
style = "bold blue"
ssh_symbol = " "

# DIRECTORY
[directory]
style = "bold purple"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = " : "
read_only = " "

# GIT
[git_branch]
style = "bold purple"
symbol = "🪵 "

[git_status]
ahead = "${count}"
behind = "${count}"
deleted = "x"
diverged = "${ahead_count}${behind_count}"
style = "text"

[git_metrics]
disabled = false
added_style = 'bold green'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

# BATTERY
[battery]
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '
full_symbol = '󰁹 '
unknown_symbol = "󰁽 "
format = "[$symbol$percentage]($style) "
disabled = true

[[battery.display]]
threshold = 10
style = 'bold warning_red'

[[battery.display]]
threshold = 90
style = "bold yellow"

[[battery.display]]
threshold = 90
style = "bold green"

# MEMORY USAGE
[memory_usage]
threshold = -1
disabled = false
format = "$symbol[${ram}]($style) "
symbol = "󰍛 "
style = "bold yellow"

# OS
[os]
disabled = false
format = "[$symbol]($style)"
style = "bold purple"

# SUDO
[sudo]
symbol = "🧙 "
format = "[as $symbol]($style)"
style = "bold blue"
disabled = false

[palettes.catppuccin_mocha]
purple = '#B7A3E3'
blue = '#77BEF0'
green = '#67C090'
brilliant_green = '#08CB00'
red = '#EA5B6F'
warning_red = '#7D0A0A'
yellow = '#FFCB61'
orange = '#FF894F'

# SYMBOLS
[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Garuda = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
disabled = false
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
style = "bold green"
version_format = "v${raw}"
detect_extensions = [ "py", "ipynb" ]

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
